export const LOGIN_SUCCESS = 'act/LOGIN_SUCCESS';
export const AUTHENTICATE = 'act/AUTHENTICATE';
export const SET_DID_TRY_AL = 'act/SET_DID_TRY_AL';
export const LOGOUT = 'act/LOGOUT';
export const DETAIL_PERMOHONAN_START = 'act/DETAIL_PERMOHONAN_START';
export const DETAIL_PERMOHONAN_SUCCESS = 'act/DETAIL_PERMOHONAN_SUCCESS';
export const DETAIL_PERMOHONAN_FAIL = 'act/DETAIL_PERMOHONAN_FAIL';

export const NOTIFIKASI_START = 'act/NOTIFIKASI_START';
